name: Deploy to SSH server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Deploy
      env:
        SLACK_MESSAGE: " * Initialize deploy of Olimed to Hostinger Server :git:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      env:
        SLACK_MESSAGE: " * Installing Dependencies :npm:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        npm install
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Build
      env:
        SLACK_MESSAGE: " * Building React App Dist Folder :vite:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        npm run build
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add host key to known host
      env:
        SLACK_MESSAGE: " * Set Connection and Enable it to SSH SERVER :hostinger:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        ssh-keyscan -p 65002 145.14.151.58 >> ~/.ssh/known_hosts
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Deploy
      env:
        SLACK_MESSAGE: " * App Deployed Successfully :react: :typescript:"
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "${SLACK_MESSAGE}"
        scp -P 65002 -r dist/* u996714911@145.14.151.58:/home/u996714911/domains/olimed.com.pe/public_html/
        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"${SLACK_MESSAGE}"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
